name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Yarn install and release
        env:
          GH_TOKEN: ${{GH_TOKEN}}
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          pnpm run electron:release-all
